### ISSUE TITLE
3주차 할 것

### ISSUE THREAD

**Issue by Seon-woong** [Coffee-Street/Document#2]
## Planning

* [ ] 새로 받은 UI / UX 문서 분석 후 공유, 앞으로 나아가야 할 문서 초안 정리
* [x] Github, Git, Source Tree 사용법 교육 받기
* [x] Github Issue 사용법 교육 받기

**Comment by wnsgml972** [comment]
@Seon-woong 기간 지났으면 Issue Close 해줘~~ 여기서 Close 하면 Project 칸반 보드에서 알아서 Done으로 변경 됨!
